### ISSUE TITLE
npm translator cannot handle cyclic dependencies

### ISSUE THREAD

**Issue by kristian** [SAP/ui5-project#50]
## Expected Behavior
Cyclic dependencies are resolved, by introducing a cycle breaker, if any dependency was already visited.

## Current Behavior
`ui5 serve` as well as `ui5 tree` will not yield any result.

## Steps to reproduce the issue
1. Introduce a cyclic dependency in two dependend project, e.g. project A depends B, project B depends A.
2. Try to `ui5 serve`, `ui5 tree`

## Affected components
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [x] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Stack trace/log output
```
verb cli:middlewares:base using node version v10.11.0
verb normalizer:normalizer Building dependency tree...
verb normalizer:translators:npm Analyzing project-a ([somepath]\components\a) (dependency of nothing - root project)
verb normalizer:translators:npm Analyzing project-b ([somepath]\components\b) (dependency of project-a)
verb normalizer:translators:npm Analyzing project-c ([somepath]\components\c) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/sap.m ([somepath]\openui5\src\sap.m) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/sap.ui.layout ([somepath]\openui5\src\sap.ui.layout) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/sap.f ([somepath]\openui5\src\sap.f) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/sap.ui.core ([somepath]\openui5\src\sap.ui.core) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/themelib_sap_belize ([somepath]\openui5\src\themelib_sap_belize) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/sap.ui.unified ([somepath]\openui5\src\sap.ui.unified) (dependency of @openui5/sap.m)
verb normalizer:translators:npm Analyzing project-a ([somepath]\components\a) (dependency of project-c)
```

**Comment by codeworrior** [comment]
IMO cyclic dependencies should be avoided in general. There exist build steps that require that  all dependencies have been built already.

In the presence of cycles, no build order could be established for such build steps.

To `ui5 serve` and `ui5 tree` this doesn't apply.

**Comment by kristian** [comment]
Hello Frank. Generally I also think cyclic depdendencies should be avoided whenever possible. Now the UI5 build tooling with the NPM translator is using NPM dependencies as a way to determine which applications and libraries to put in the build/serve path. Maybe I can explain my use case a little better using an example:

Say `project-a` is our application dependency. The application shoud load / display other components like `project-b` (which are currently built as library, until https://github.com/SAP/ui5-tooling/issues/45 is done). `project-b` is built independently from our application `project-a`, so they add `project-a` as a `devDependency` for testing. When `ui5 serve`ing, the application will start and display the new component in the application `project-a`. 

Now deveopment is done and we would actually like to embed `project-b` into `project-a`, so we would add `project-b` as a `dependency` of `project-a` and therefore create a cycle. So either:

1. Applications will have to remove their `devDependencies` as soon as they are included into the parent project,
2. You add logic to detect & break such cycles
3. You could add a flag to only follow `dependencies` when building and serving the tree or
4. You don't consider this as a use-case at all (which I also think would be completely fine tbh.!), so I will have to take care about loading the dependent components on runtime.

Option 1. and 4. even beeing the clearest to be, in case you don't want to support cycles in the build tooling which I could fully understand. =) Hope that made it a little bit more clear.

> To ui5 serve and ui5 tree this doesn't apply.

One improvement I'd consider doing in any case, is to at least have a log-output or even an error for the CLI tooling. Because at the moment ui5 serve / tree will simply output literally nothing is verbose logging is disabled.

**Comment by RandomByte** [comment]
This sounds similar to the structure of the [UI5Lab](https://github.com/UI5Lab) project:
![screenshot 2018-10-22 at 13 35 32](https://user-images.githubusercontent.com/1589939/47290403-9b14ab80-d5ff-11e8-9082-b3f97f04e69e.png)

Basically, the component needs the main application for testing. Also, the libraries require the component for testing.

In case of the UI5Lab project, the Main Application would be [UI5Lab-central](https://github.com/UI5Lab/UI5Lab-central), Component A would be [UI5Lab-browser](https://github.com/UI5Lab/UI5Lab-browser) and the libraries something like [UI5Lab-library-simple](https://github.com/UI5Lab/UI5Lab-library-simple).

**Comment by kristian** [comment]
Hey Merlin! Yes, that's exactly what we'd like to accomplish! **Awesome example!** Thanks a lot for that.

Unfortunately it seems that currently these kinds of dev. / non-dev. depenpency cylces are not supported by the node build tooling, or more specificly by the npm translator yet. So essentially this bug could be drilled down that path. @codeworrior, what do you think?

**Comment by RandomByte** [comment]
Possibly related to https://github.com/SAP/ui5-project/issues/14

**Comment by RandomByte** [comment]
I tried to create a test case with https://github.com/SAP/ui5-project/pull/53, however I'm not getting the same result as you reported.

When checking out #53 and navigating to `test/fixtures/cyclic-deps/application.cycle`, executing `ui5 tree` actually returns a dependency tree containing `(circular ref.)`.

Did I get you right that you executed `ui5 tree` in the (root) **application** project? Does your setup differ from that outlined in https://github.com/SAP/ui5-project/issues/50#issuecomment-431812960?

**Comment by kristian** [comment]
Hello Merlin, as said, I can still reproduce the problem if I put the root project as a `dependency` (not an `devDependency`) in the component project. If I do so and execute `ui5 tree --verbose`, I can reproduce the issue:

```
verb cli:middlewares:base using node version v10.11.0
verb normalizer:normalizer Building dependency tree...
verb normalizer:translators:npm Analyzing project-a ([somepath]\components\a) (dependency of nothing - root project)
verb normalizer:translators:npm Analyzing project-b ([somepath]\components\b) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/sap.f ([somepath]\openui5\src\sap.f) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/sap.ui.layout ([somepath]\openui5\src\sap.ui.layout) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/sap.m ([somepath]\openui5\src\sap.m) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/sap.ui.core ([somepath]\openui5\src\sap.ui.core) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/themelib_sap_belize ([somepath]\openui5\src\themelib_sap_belize) (dependency of project-a)
verb normalizer:translators:npm Analyzing @openui5/sap.ui.unified ([somepath]\openui5\src\sap.ui.unified) (dependency of @openui5/sap.m)
verb normalizer:translators:npm Analyzing project-a ([somepath]\components\a) (dependency of project-b)
```

`ui5 serve --verbose` will output the same result and quit. If I put the dependency to the root project as a `devDependency` in the component project, `ui5 tree` will (as you said) yield the correct result and the tree includes a "(circular ref.)". Still I can also reproduce your error with `ui5 serve` the result will be:

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at ProjectPreprocessor.loadProjectConfiguration
```

So this should be a bug for the server, rather than with the project builder I guess.

**Comment by RandomByte** [comment]
> I can still reproduce the problem if I put the root project as a dependency (not an devDependency) in the component project.

Like this?
```
root-project package.json:
    dependencies: {
        "component-project"
	}


component-project package.json:
    dependencies: {
        "root-project"
	}
```

If yes, that's a circle. Executing `npm install` in the root-project of a similar test setup on my system has npm version `6.4.1` stuck in a loop until the maximum call stack size is exceeded:
![npm install circle](https://user-images.githubusercontent.com/1589939/48212719-7e58d180-e37c-11e8-9844-030340b68d00.gif)

I think we can agree that *this* kind of circular dependency should not be supported, right? Still, error handling would be nice.

---

> If I put the dependency to the root project as a devDependency in the component project, ui5 tree will (as you said) yield the correct result and the tree includes a "(circular ref.)".

That's the only use case I think we should make work here. I'm not yet sure whether the tree generated by UI5 Project or the handling in the UI5 Server needs adaption for that.

**Comment by kristian** [comment]
> I think we can agree that this kind of circular dependency should not be supported, right? Still, error handling would be nice.
Agreed.

> That's the only use case I think we should make work here.
Agreed. =)

**Comment by RandomByte** [comment]
So, the initial issue should be fixed through https://github.com/SAP/ui5-project/pull/53 and https://github.com/SAP/ui5-project/pull/78. The tooling should now be capable of handling cyclic dependencies. 

This can be tested with UI5 CLI v0.2.8.

However, the setup I outlined in my [comment](https://github.com/SAP/ui5-project/issues/50#issuecomment-431812960) for UI5Lab might still not be possible. Not because of cyclic dependencies, but because of the fact that devDependencies are ignored by the tooling, unless the dependency is listed in "dependencies" of another project of the current dependency tree. This means that for the picture below, when starting the ui5 server in "Component A", the project "Main Application" would not be served, as no project declares a non-dev dependency to it.  

![47290403-9b14ab80-d5ff-11e8-9082-b3f97f04e69e](https://user-images.githubusercontent.com/1589939/50341432-08b95700-051f-11e9-8656-e08fa1516f41.png)

For this kind of setup, the currently only possible solution would be to create an additional module that "Main Application" as well as "Component A" can depend on (i.e. remove the cycle).

---

I'll close this incident for now as the npm translator can now handle cyclic dependencies. Thanks for reporting!
